### ISSUE TITLE
Not clear regarding gamma!!

### ISSUE THREAD

**Issue by chaiban** [sdoria/SimpleSelfAttention#3]
self.gamma = nn.Parameter(tensor([0.]))  

o = self.gamma * o + x 
or 
o = self.gamma * torch.bmm(h, beta) + x 

Hi @sdoria ,

I have a problem understanding the code. If we set gamma to 0., then wouldn't that always be zero ? 

where is the atention ? As gamma is zero the complete self-attention is zero and the code finally adds input and pass it to linear. 

I dont see the self attention here.

May be i did not understand it clearly, would you mind clarifying that?

Thanks!

**Comment by webbie321** [comment]
hey it's been a couple years since I've looked at this code or done anything in machine learning, but I'll try. Possibly gamma is only initiated at 0 and then its value is learned within the model?

**Comment by chaiban** [comment]
Yes, I think so too. Thanks! I referred to original code and it is correct.
